# -*- coding: utf-8 -*-
"""SmartATM: Python-based Banking Simulation.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/103sYuTT-TL-35PA-1tkNXCPnXlYbWb_5
"""

class Atm:
  def __init__(self):
    self.Balance=100000
    self.account_no=12345
    self.pin=None
    self.display()

  #Display Section
  def display(self):
    user_input=input('''Welcome to our Atm service:
              what you want to perform:
              1. Genereate pin
              2. Withdrawal Money
              3. Deposit
              4. Balance Enquiry
              5. Exit''')
    if user_input=="1":
      self.generate_pin()
    elif user_input=="2":
      self.Withdrawal()
    elif user_input=="3":
      self.Deposit()
    elif user_input=="4":
      self.Balance_enquiry()
    else:
      exit()

  def generate_pin(self):
    user_pin=int(input("Enter three digit Pin"))
    self.pin=user_pin
    print("Pin generated succussefully")
    self.display()

  def Withdrawal(self):
    user_pinw=int(input("Enter three digit Pin"))
    if self.pin==user_pinw:
      amount=int(input("Enter amount you want to withdrawl"))
      if self.Balance < amount:
        print("Insufficient balance")
      else:
        self.Balance=self.Balance-amount
        print("Withdrwal sucessfull",amount)
        self.display()
    else:
      print("Invalid Pin: ")
      self.Withdrawal()

  #Deposit
  def Deposit(self):
    user_pind=int(input("Enter three digit Pin"))
    if self.pin==user_pind:
      amount1=int(input("Enter amount you want to Credit"))
      self.Balance +=amount1
      print("Balance deposition successfull")
      self.display()
    else:
      print("Invalid Pin: ")
      self.Deposit()

  #Balance Enquiry
  def Balance_enquiry(self):
    user_pinb=int(input("Enter three digit Pin"))
    if self.pin==user_pinb:
      print("Your balalance is: ", self.Balance)

    else:
        print("Invalid Pin: ")
        self.Balance_enquiry()

sbi = Atm()
